In [1]:
import numpy as np
from scipy.sparse import dok_matrix

In [2]:
with open("/Users/anilaswani/Desktop/web-Stanford.txt") as f:
    contents = f.readlines()

In [3]:
A = np.zeros((10, 10))
B = np.ones((10, 10))

In [4]:
for pair in contents:
    pair.replace("\n","")
    coord = pair.split(" ")
    c1 = int(coord[0])
    c2 = int(coord[1])
    A[c1][c2]=1

In [5]:
A = A/A.sum(axis=0, keepdims=True)

In [6]:
v = np.array([[1/10],[1/10],[1/10],[1/10],[1/10],[1/10],[1/10],[1/10],[1/10],[1/10]])
print((v.shape))

(10, 1)


In [7]:
p=0.85
M = p*A + (1-p)*B
M = np.round_(M, decimals = 3)
print(M)

[[0.15  0.15  0.15  0.15  0.15  0.15  0.15  0.15  0.15  0.15 ]
 [0.15  0.15  0.15  0.256 0.15  0.363 0.15  0.433 0.433 0.292]
 [0.575 0.15  0.15  0.256 0.15  0.363 0.32  0.15  0.15  0.292]
 [0.15  0.15  0.433 0.15  0.15  0.15  0.32  0.15  0.15  0.15 ]
 [0.15  0.15  0.15  0.256 0.15  0.363 0.15  0.15  0.15  0.292]
 [0.575 0.15  0.15  0.256 0.15  0.15  0.32  0.433 0.433 0.292]
 [0.15  0.575 0.433 0.256 0.575 0.15  0.15  0.15  0.15  0.15 ]
 [0.15  0.15  0.433 0.256 0.15  0.15  0.32  0.15  0.15  0.292]
 [0.15  0.575 0.15  0.256 0.15  0.363 0.15  0.433 0.15  0.292]
 [0.15  0.15  0.15  0.256 0.575 0.15  0.32  0.15  0.433 0.15 ]]


In [8]:
temp = M

In [9]:
print(v)

[[0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]
 [0.1]]


In [10]:
i=0
while(i < 10):
    vnew = np.matmul(M,v)
    vnew = np.round_(vnew, decimals = 2)
    if(all(vnew==v)):
        break
    i=i+1
    v = vnew

In [11]:
print(v)

[[327.91]
 [566.51]
 [538.09]
 [435.65]
 [435.84]
 [613.18]
 [593.64]
 [488.01]
 [597.06]
 [541.23]]


In [12]:
np.argsort(v.transpose(), axis=-1, kind='quicksort', order=None)

array([[0, 3, 4, 7, 2, 9, 1, 6, 8, 5]])